//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34014
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ResManDeadlock {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Forms {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Forms() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ResManDeadlock.Forms", typeof(Forms).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Active Forms are available for the users to add records.
        /// </summary>
        public static string formEdit_activeButton_title {
            get {
                return ResourceManager.GetString("formEdit_activeButton_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        public static string formEdit_cancel {
            get {
                return ResourceManager.GetString("formEdit_cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete form.
        /// </summary>
        public static string formEdit_delete_form {
            get {
                return ResourceManager.GetString("formEdit_delete_form", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you really want to delete this form?.
        /// </summary>
        public static string formEdit_do_you_want_to_delete {
            get {
                return ResourceManager.GetString("formEdit_do_you_want_to_delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Draft form can be modified however nobody can add records to it..
        /// </summary>
        public static string formEdit_draftButton_title {
            get {
                return ResourceManager.GetString("formEdit_draftButton_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Send notification when new record is submitted.
        /// </summary>
        public static string formNotifications_Text {
            get {
                return ResourceManager.GetString("formNotifications_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date is not valid..
        /// </summary>
        public static string formRecords_InvalidDate {
            get {
                return ResourceManager.GetString("formRecords_InvalidDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to - Please select project -.
        /// </summary>
        public static string FormsConversion_PleaseSelect {
            get {
                return ResourceManager.GetString("FormsConversion_PleaseSelect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Project to add converted activities:.
        /// </summary>
        public static string FormsConversion_ProjectForActivityDescription {
            get {
                return ResourceManager.GetString("FormsConversion_ProjectForActivityDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add field or label to the form.
        /// </summary>
        public static string formsEdit_addFiledOrLabel {
            get {
                return ResourceManager.GetString("formsEdit_addFiledOrLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add new field or label to the form.
        /// </summary>
        public static string formsEdit_addFiledOrLabel_Title {
            get {
                return ResourceManager.GetString("formsEdit_addFiledOrLabel_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create.
        /// </summary>
        public static string formsEdit_addNew {
            get {
                return ResourceManager.GetString("formsEdit_addNew", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Allow access for Anonymous Users.
        /// </summary>
        public static string formsEdit_anonymousUsers {
            get {
                return ResourceManager.GetString("formsEdit_anonymousUsers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Apply.
        /// </summary>
        public static string formsEdit_Apply {
            get {
                return ResourceManager.GetString("formsEdit_Apply", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Archive.
        /// </summary>
        public static string formsEdit_archive {
            get {
                return ResourceManager.GetString("formsEdit_archive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Building Blocks.
        /// </summary>
        public static string formsEdit_buildingblocks {
            get {
                return ResourceManager.GetString("formsEdit_buildingblocks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        public static string formsEdit_cancel {
            get {
                return ResourceManager.GetString("formsEdit_cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change element settings.
        /// </summary>
        public static string formsEdit_changeElementSettings {
            get {
                return ResourceManager.GetString("formsEdit_changeElementSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Checkboxes label.
        /// </summary>
        public static string formsEdit_CheckboxesLabel {
            get {
                return ResourceManager.GetString("formsEdit_CheckboxesLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Click on element to build your form.
        /// </summary>
        public static string formsEdit_clickToBuildForm {
            get {
                return ResourceManager.GetString("formsEdit_clickToBuildForm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Close.
        /// </summary>
        public static string formsEdit_closeBtnTitle {
            get {
                return ResourceManager.GetString("formsEdit_closeBtnTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Conversion: .
        /// </summary>
        public static string formsEdit_conversionRulesTitle {
            get {
                return ResourceManager.GetString("formsEdit_conversionRulesTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Form to Issue.
        /// </summary>
        public static string formsEdit_conversionToIssue {
            get {
                return ResourceManager.GetString("formsEdit_conversionToIssue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please choose how fields from this form should be mapped to a new issue..
        /// </summary>
        public static string formsEdit_conversionToIssueDescription {
            get {
                return ResourceManager.GetString("formsEdit_conversionToIssueDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Form to Project.
        /// </summary>
        public static string formsEdit_conversionToProject {
            get {
                return ResourceManager.GetString("formsEdit_conversionToProject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please choose how fields from this form should be mapped to a new project..
        /// </summary>
        public static string formsEdit_conversionToProjectDescription {
            get {
                return ResourceManager.GetString("formsEdit_conversionToProjectDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Form to Request.
        /// </summary>
        public static string formsEdit_conversionToRequest {
            get {
                return ResourceManager.GetString("formsEdit_conversionToRequest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please choose how fields from this form should be mapped to a new request..
        /// </summary>
        public static string formsEdit_conversionToRequestDescription {
            get {
                return ResourceManager.GetString("formsEdit_conversionToRequestDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Form to Task.
        /// </summary>
        public static string formsEdit_conversionToTask {
            get {
                return ResourceManager.GetString("formsEdit_conversionToTask", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please choose how fields from this form should be mapped to a new task..
        /// </summary>
        public static string formsEdit_conversionToTaskDescription {
            get {
                return ResourceManager.GetString("formsEdit_conversionToTaskDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Guest Users.
        /// </summary>
        public static string formsEdit_customerUsers {
            get {
                return ResourceManager.GetString("formsEdit_customerUsers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date.
        /// </summary>
        public static string formsEdit_date {
            get {
                return ResourceManager.GetString("formsEdit_date", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Define form states (0) .
        /// </summary>
        public static string formsEdit_defineFormStatesFirst {
            get {
                return ResourceManager.GetString("formsEdit_defineFormStatesFirst", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to to process submitted records..
        /// </summary>
        public static string formsEdit_defineFormStatesSecond {
            get {
                return ResourceManager.GetString("formsEdit_defineFormStatesSecond", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete.
        /// </summary>
        public static string formsEdit_delete {
            get {
                return ResourceManager.GetString("formsEdit_delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete.
        /// </summary>
        public static string formsEdit_deleteField {
            get {
                return ResourceManager.GetString("formsEdit_deleteField", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        public static string formsEdit_deleteFieldCancel {
            get {
                return ResourceManager.GetString("formsEdit_deleteFieldCancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to delete this field?.
        /// </summary>
        public static string formsEdit_deleteFieldConfirmation {
            get {
                return ResourceManager.GetString("formsEdit_deleteFieldConfirmation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete or Archive this form.
        /// </summary>
        public static string formsEdit_deleteOrArchiveThisForm {
            get {
                return ResourceManager.GetString("formsEdit_deleteOrArchiveThisForm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Specify a brief description for this form.
        /// </summary>
        public static string formsEdit_description {
            get {
                return ResourceManager.GetString("formsEdit_description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Design your form.
        /// </summary>
        public static string formsEdit_designYourForm {
            get {
                return ResourceManager.GetString("formsEdit_designYourForm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Discard changes.
        /// </summary>
        public static string formsEdit_discard {
            get {
                return ResourceManager.GetString("formsEdit_discard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dropdown.
        /// </summary>
        public static string formsEdit_dropdown {
            get {
                return ResourceManager.GetString("formsEdit_dropdown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit.
        /// </summary>
        public static string formsEdit_edit {
            get {
                return ResourceManager.GetString("formsEdit_edit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email will be sent to an address in the selected field or, if empty, to the submitter..
        /// </summary>
        public static string formsEdit_emailWillBeSent {
            get {
                return ResourceManager.GetString("formsEdit_emailWillBeSent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This element can be used to provide help or description for any item on the form..
        /// </summary>
        public static string formsEdit_exampleParagraphText {
            get {
                return ResourceManager.GetString("formsEdit_exampleParagraphText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Example paragraph.
        /// </summary>
        public static string formsEdit_exampleParagraphTitle {
            get {
                return ResourceManager.GetString("formsEdit_exampleParagraphTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File attachment.
        /// </summary>
        public static string formsEdit_file {
            get {
                return ResourceManager.GetString("formsEdit_file", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Сustom Form.
        /// </summary>
        public static string formsEdit_form {
            get {
                return ResourceManager.GetString("formsEdit_form", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Guest Portal.
        /// </summary>
        public static string formsEdit_guestUsers {
            get {
                return ResourceManager.GetString("formsEdit_guestUsers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Make form available to all Guest users.
        /// </summary>
        public static string formsEdit_guestUsersDescription {
            get {
                return ResourceManager.GetString("formsEdit_guestUsersDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Heading.
        /// </summary>
        public static string formsEdit_heading {
            get {
                return ResourceManager.GetString("formsEdit_heading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You’re about to create a new form. Steps include: designing form layout and deciding who and how can access it. Once the form is Active, people will be able to start using it (adding records)..
        /// </summary>
        public static string formsEdit_help {
            get {
                return ResourceManager.GetString("formsEdit_help", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Click to read some hints on form design.
        /// </summary>
        public static string formsEdit_help_title {
            get {
                return ResourceManager.GetString("formsEdit_help_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Input.
        /// </summary>
        public static string formsEdit_input {
            get {
                return ResourceManager.GetString("formsEdit_input", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Label.
        /// </summary>
        public static string formsEdit_label {
            get {
                return ResourceManager.GetString("formsEdit_label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to label 1.
        /// </summary>
        public static string formsEdit_Label1 {
            get {
                return ResourceManager.GetString("formsEdit_Label1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to label 2.
        /// </summary>
        public static string formsEdit_Label2 {
            get {
                return ResourceManager.GetString("formsEdit_Label2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to label 3.
        /// </summary>
        public static string formsEdit_Label3 {
            get {
                return ResourceManager.GetString("formsEdit_Label3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to label 4.
        /// </summary>
        public static string formsEdit_Label4 {
            get {
                return ResourceManager.GetString("formsEdit_Label4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to List of checkboxes.
        /// </summary>
        public static string formsEdit_listOfChackboxes {
            get {
                return ResourceManager.GetString("formsEdit_listOfChackboxes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to List of options.
        /// </summary>
        public static string formsEdit_listOptions {
            get {
                return ResourceManager.GetString("formsEdit_listOptions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Make form available for Customer Portal users..
        /// </summary>
        public static string formsEdit_makeAvailibleForCP {
            get {
                return ResourceManager.GetString("formsEdit_makeAvailibleForCP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please add fields first..
        /// </summary>
        public static string formsEdit_noFields {
            get {
                return ResourceManager.GetString("formsEdit_noFields", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Send confirmation.
        /// </summary>
        public static string formsEdit_NotifyRecordCreator {
            get {
                return ResourceManager.GetString("formsEdit_NotifyRecordCreator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select email field.
        /// </summary>
        public static string formsEdit_NotifySelectDefault {
            get {
                return ResourceManager.GetString("formsEdit_NotifySelectDefault", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your changes will be lost. Do you want to leave this page without save changes?.
        /// </summary>
        public static string formsEdit_notSavedChangesMessage {
            get {
                return ResourceManager.GetString("formsEdit_notSavedChangesMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dropdown.
        /// </summary>
        public static string formsEdit_onboardingDropdown {
            get {
                return ResourceManager.GetString("formsEdit_onboardingDropdown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add element from library.
        /// </summary>
        public static string formsEdit_onboardingHint1 {
            get {
                return ResourceManager.GetString("formsEdit_onboardingHint1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change fields order.
        /// </summary>
        public static string formsEdit_onboardingHint2 {
            get {
                return ResourceManager.GetString("formsEdit_onboardingHint2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change fields settings.
        /// </summary>
        public static string formsEdit_onboardingHint3 {
            get {
                return ResourceManager.GetString("formsEdit_onboardingHint3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Here is how things work:.
        /// </summary>
        public static string formsEdit_onboardingTitle {
            get {
                return ResourceManager.GetString("formsEdit_onboardingTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Option A.
        /// </summary>
        public static string formsEdit_optionOneCanAlsoBeChecked {
            get {
                return ResourceManager.GetString("formsEdit_optionOneCanAlsoBeChecked", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Options.
        /// </summary>
        public static string formsEdit_optionsLabel {
            get {
                return ResourceManager.GetString("formsEdit_optionsLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Option B.
        /// </summary>
        public static string formsEdit_optionTwoCanAlsoBeChecked {
            get {
                return ResourceManager.GetString("formsEdit_optionTwoCanAlsoBeChecked", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to or.
        /// </summary>
        public static string formsEdit_or {
            get {
                return ResourceManager.GetString("formsEdit_or", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Preview.
        /// </summary>
        public static string formsEdit_preview {
            get {
                return ResourceManager.GetString("formsEdit_preview", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Preview.
        /// </summary>
        public static string formsEdit_preview_Title {
            get {
                return ResourceManager.GetString("formsEdit_preview_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Active.
        /// </summary>
        public static string formsEdit_publish {
            get {
                return ResourceManager.GetString("formsEdit_publish", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Radio button list.
        /// </summary>
        public static string formsEdit_radio {
            get {
                return ResourceManager.GetString("formsEdit_radio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Field is required.
        /// </summary>
        public static string formsEdit_Required {
            get {
                return ResourceManager.GetString("formsEdit_Required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Restore into Draft.
        /// </summary>
        public static string formsEdit_restore_into_draft {
            get {
                return ResourceManager.GetString("formsEdit_restore_into_draft", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Back to forms.
        /// </summary>
        public static string formsEdit_returnToForms {
            get {
                return ResourceManager.GetString("formsEdit_returnToForms", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Draft.
        /// </summary>
        public static string formsEdit_saveAsDraft {
            get {
                return ResourceManager.GetString("formsEdit_saveAsDraft", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save changes.
        /// </summary>
        public static string formsEdit_saveChanges {
            get {
                return ResourceManager.GetString("formsEdit_saveChanges", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Separator.
        /// </summary>
        public static string formsEdit_separator {
            get {
                return ResourceManager.GetString("formsEdit_separator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show code.
        /// </summary>
        public static string formsEdit_showCode {
            get {
                return ResourceManager.GetString("formsEdit_showCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manage conversion to projects and activities.
        /// </summary>
        public static string formsEdit_ShowConversionRules {
            get {
                return ResourceManager.GetString("formsEdit_ShowConversionRules", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show link.
        /// </summary>
        public static string formsEdit_showLink {
            get {
                return ResourceManager.GetString("formsEdit_showLink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Text area.
        /// </summary>
        public static string formsEdit_textArea {
            get {
                return ResourceManager.GetString("formsEdit_textArea", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Specify name for this form.
        /// </summary>
        public static string formsEdit_title {
            get {
                return ResourceManager.GetString("formsEdit_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New element.
        /// </summary>
        public static string formsEdit_titleNewElement {
            get {
                return ResourceManager.GetString("formsEdit_titleNewElement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This is required field..
        /// </summary>
        public static string formsEdit_titleRequired {
            get {
                return ResourceManager.GetString("formsEdit_titleRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to People who are not Easy Projects users will be able to add new records to this form..
        /// </summary>
        public static string formsEdit_userWillBeAbleToAddNewRecords {
            get {
                return ResourceManager.GetString("formsEdit_userWillBeAbleToAddNewRecords", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to What to do next:.
        /// </summary>
        public static string formsEdit_whatDoNext {
            get {
                return ResourceManager.GetString("formsEdit_whatDoNext", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You can use this HTML code to integrate the form into your web-site..
        /// </summary>
        public static string formsEdit_youCanUseHtml {
            get {
                return ResourceManager.GetString("formsEdit_youCanUseHtml", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Notifications.
        /// </summary>
        public static string formsNotifications {
            get {
                return ResourceManager.GetString("formsNotifications", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add records.
        /// </summary>
        public static string formsPermissions_AddRecords {
            get {
                return ResourceManager.GetString("formsPermissions_AddRecords", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add users or teams.
        /// </summary>
        public static string formsPermissions_AddUsersOrTeams {
            get {
                return ResourceManager.GetString("formsPermissions_AddUsersOrTeams", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you really want to exclude this user?.
        /// </summary>
        public static string formsPermissions_do_you_want_to_delete {
            get {
                return ResourceManager.GetString("formsPermissions_do_you_want_to_delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you really want to exclude this team?.
        /// </summary>
        public static string formsPermissions_do_you_want_to_delete_team {
            get {
                return ResourceManager.GetString("formsPermissions_do_you_want_to_delete_team", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit and handle records.
        /// </summary>
        public static string formsPermissions_EditRecords {
            get {
                return ResourceManager.GetString("formsPermissions_EditRecords", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Custom Form.
        /// </summary>
        public static string formsPermissions_FormTitle {
            get {
                return ResourceManager.GetString("formsPermissions_FormTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manage Custom Form and records.
        /// </summary>
        public static string formsPermissions_ManageCustomForm {
            get {
                return ResourceManager.GetString("formsPermissions_ManageCustomForm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nobody can yet access the form..
        /// </summary>
        public static string formsPermissions_No_DisplayUsersAndTeams {
            get {
                return ResourceManager.GetString("formsPermissions_No_DisplayUsersAndTeams", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Records.
        /// </summary>
        public static string formsPermissions_RecordsTitle {
            get {
                return ResourceManager.GetString("formsPermissions_RecordsTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Specify who can access this form.
        /// </summary>
        public static string formsPermissions_SpecifyTitle {
            get {
                return ResourceManager.GetString("formsPermissions_SpecifyTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View all records.
        /// </summary>
        public static string formsPermissions_ViewRecords {
            get {
                return ResourceManager.GetString("formsPermissions_ViewRecords", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Everyone.
        /// </summary>
        public static string GroupEveryone {
            get {
                return ResourceManager.GetString("GroupEveryone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Predefined user groups.
        /// </summary>
        public static string GroupsSelector {
            get {
                return ResourceManager.GetString("GroupsSelector", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete element.
        /// </summary>
        public static string ItemHolder_Delete_Row_Title {
            get {
                return ResourceManager.GetString("ItemHolder_Delete_Row_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change element settings.
        /// </summary>
        public static string ItemHolder_Edit_Row_Title {
            get {
                return ResourceManager.GetString("ItemHolder_Edit_Row_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Drag to reorder.
        /// </summary>
        public static string ItemHolder_Order_Row_Title {
            get {
                return ResourceManager.GetString("ItemHolder_Order_Row_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Make form available to external users and your clients:.
        /// </summary>
        public static string makeFormAvailibleForExternal {
            get {
                return ResourceManager.GetString("makeFormAvailibleForExternal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Close.
        /// </summary>
        public static string PopUp_CloseWindow_Title {
            get {
                return ResourceManager.GetString("PopUp_CloseWindow_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        public static string Record_Delete_Cancel_Text {
            get {
                return ResourceManager.GetString("Record_Delete_Cancel_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        public static string Record_Delete_Cancel_Title {
            get {
                return ResourceManager.GetString("Record_Delete_Cancel_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you really want to delete this record?.
        /// </summary>
        public static string Record_Delete_Confirmation_Message {
            get {
                return ResourceManager.GetString("Record_Delete_Confirmation_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete.
        /// </summary>
        public static string Record_Delete_Delete_Text {
            get {
                return ResourceManager.GetString("Record_Delete_Delete_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete this record.
        /// </summary>
        public static string Record_Delete_Delete_Title {
            get {
                return ResourceManager.GetString("Record_Delete_Delete_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No records to display.
        /// </summary>
        public static string Record_No_Records_To_Display_Text {
            get {
                return ResourceManager.GetString("Record_No_Records_To_Display_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No record to display or you do not have permissions to see it.
        /// </summary>
        public static string Record_No_Records_To_Display_Text_PermanentLink {
            get {
                return ResourceManager.GetString("Record_No_Records_To_Display_Text_PermanentLink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Teams.
        /// </summary>
        public static string TeamsSelector {
            get {
                return ResourceManager.GetString("TeamsSelector", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add new element to the form.
        /// </summary>
        public static string Templates_AddNew_Title {
            get {
                return ResourceManager.GetString("Templates_AddNew_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Value 1.
        /// </summary>
        public static string Templates_DropDown_ValueOne {
            get {
                return ResourceManager.GetString("Templates_DropDown_ValueOne", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Value 2.
        /// </summary>
        public static string Templates_DropDown_ValueTwo {
            get {
                return ResourceManager.GetString("Templates_DropDown_ValueTwo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choose file.
        /// </summary>
        public static string Templates_File_ChooseFile {
            get {
                return ResourceManager.GetString("Templates_File_ChooseFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No file chosen.
        /// </summary>
        public static string Templates_File_DefaultText {
            get {
                return ResourceManager.GetString("Templates_File_DefaultText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Option A.
        /// </summary>
        public static string Templates_Radio_OptionOne {
            get {
                return ResourceManager.GetString("Templates_Radio_OptionOne", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Option B.
        /// </summary>
        public static string Templates_Radio_OptionTwo {
            get {
                return ResourceManager.GetString("Templates_Radio_OptionTwo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Users.
        /// </summary>
        public static string UsersSelector {
            get {
                return ResourceManager.GetString("UsersSelector", resourceCulture);
            }
        }
    }
}
